apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: contour
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/cluster1/coral-system/ManifestDeployments/contour/all
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
